#!/bin/bash
### PURPOSE OF THE SCRIPT: remove Z chromosome (NC_031799.1) from the 
### matrix of methylation values per position generated by the script
### 06_RDA°methylation_data.R

mkdir /PATH/TO/06_results/rda/without_Z
cd /PATH/TO/06_results/rda/sans_Z
sed '/NC_031799.1/d' merge_meth_par_position_par_indiv.txt > merge_meth_par_position_par_indiv_sans_Z.txt
